### ISSUE TITLE
Is this supported for Ubuntu server 16.04 ?

### ISSUE THREAD

**Issue by raykai** [lesaff/serverpilot-letsencrypt#2]
Is this tool supported for the new  Ubuntu server 16.04 LTS ?

If not any plans as when it could be ? 

Keep up the good work .

**Comment by lesaff** [comment]
I have not tested the script on 16.04 but since there's nothing in the bash script that is version-related, I don't see any issue with running it on newer versions.

I will eventually move my apps/sites to 16.04 and will post any updates if there's anything to change/modify. Thanks, hopefully you find the script useful.

Cheers

**Comment by raykai** [comment]
il give it a run and il let you know if it works
