### ISSUE TITLE
All my sites are not reachable anymore

### ISSUE THREAD

**Issue by kobject** [lesaff/serverpilot-letsencrypt#7]
This doesn't work for me on Ubuntu 14.04.

I always get ERROR_CONNECTION_Reset on Chrome.

**Comment by lesaff** [comment]
What did it say in the console when you ran the script? It should give you the verbose error. Usually it's because one of the conditions is not met.

Anyway, do the following
- `cd /etc/nginx-sp/vhosts.d`
- `ls *ssl*`

Is the site that you just tried to add listed there?
If so, delete that ssl file
and then restart nginx
`sudo service nginx-sp restart`

**Comment by kobject** [comment]
I fixed it my own, but i hoped this worked.

I checked the script, it seems it works properly. But at the end nothing works anymore.

**Comment by lesaff** [comment]
I will close this issue. Feel free to reopen if you ran into this again.
